# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:

jobs:
  build-ui:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.2
    - run: npm build
      working-directory: ./ui
      
      
  build-api:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
        
    - run: dotnet restore
      name: Restore Packages
      working-directory: ./api
            
    - name: Run Unit Tests
      working-directory: ./api
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      
    - name: Submit Code Coverage
      run: curl -s https://codecov.io/bash
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
    - name: Run Build
      run: dotnet build
      working-directory: ./api
      
      